airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
    path('users/', include("users.urls"))
]

flights/urls.py
from django.urls import path
from flights import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

users/urls.py
from . import views
from django.urls import path

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

flights/models.py
from django.db import models

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"
        
class Flight(models.Model):
    #CASCADE = if delete airport, delete all other related data too.
    #related_name = reverse-order relationship; from an airport, 
    #what are the flights leaving from it.
    #same goes for destination
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def is_valid_flight(self):
        return self.origin != self.destination and self.duration >= 0

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}. Duration: {self.duration}"

class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    #many to many allows for multiple relationships
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from flights.models import Flight, Airport, Passenger
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    return render(request, "flights/index.html", {
        "Flights": Flight.objects.all()
    })

def flight(request, flight_id):
    #pk = primary key, whatever it is called
    try:
        #create an object of Flight whose id equals flight ID
        flight = Flight.objects.get(pk=flight_id)
    except:
        return HttpResponse("Error, flight does not exist", status=404)
    onboardPassengers = flight.passengers.all()
    otherPassengers = Passenger.objects.exclude(flights=flight).all()

    
    return render(request, "flights/flight.html", {
        "flight": flight,
        #access passengers through related name; follow the arrow back to its origin
        "passengers": onboardPassengers,
        "non_passengers": otherPassengers
    })


def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:flight", args=[flight.id]))

users/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "users/users.html")
def login_view(request):
    #post = user logs in
    #get = load page
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            #log this user in with this request.
            login(request, user)
            #redirect back to the index function
            return HttpResponseRedirect(reverse("users:index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid credentials."
            })
    return render(request, "users/login.html")

def logout_view(request):
    #basically just sign the user out
    logout(request)
    #then we decide later where to redirect the users
    return render(request, "users/login.html", {
        "message": "Logged Out."
    })

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}

    <h1>Flight {{ flight.id }}</h1>

    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }}</li>
    </ul>

    <h2>Passengers</h2>

    <ul>
        {% for passenger in passengers %}
            <li>{{ passenger }}</li>
        {% empty %}
            <li>No passengers.</li>
        {% endfor %} 
    </ul>

    <h2>Add Passengers</h2>

    <form action="{% url 'flights:book' flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger" id="">
            {% for passenger in non_passengers %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}           
        </select>
        <input type="submit">
    </form>


    <a href="{% url 'flights:index' %}">Back to flights</a>
{% endblock %}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights</h1>
    <ul>
    {% for flight in Flights %}
    <a href="{% url 'flights:flight' flight.id %}">
        <li>
            Flight {{ flight.id }}: {{ flight.origin }} to {{ flight.destination }}
         </li> 
    </a>
       
    {% endfor %}
    </ul>
{% endblock %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights</title>
</head>
<body>
    {%block body%}
    {%endblock%}
</body>
</html>

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
    {% if message %}
        <div>
            {{ message }}
        </div>  
    {% endif %}
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="Login">
    </form>
{% endblock %}

users/templates/users/users.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>
        Welcome, {{ request.user.first_name }}
    </h1>

    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'users:logout' %}">Log out</a>
{% endblock %}